# This is a basic workflow to help you get started with Actions

name: Build and push the tagged build to production

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
        
        - name: Docker Login
          uses: docker/login-action@v1.10.0
          with:
            registry: ${{ secrets.ACR_NAME }}
            username: ${{ secrets.ACR_LOGIN }}
            password: ${{ secrets.ACR_PASSWORD }}
    
    -   name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:   
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest,${{secrets.ACR_NAME}}/contoso-website:${{ steps.fetch_version.outputs.TAG }}
          push: true
